@base-url = http://localhost:3003/api
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpa3VoIiwiaWQiOiI1ZjVjYTBmZTM5YzVjNzY0YTY0NmUwYmQiLCJpYXQiOjE1OTk5MDc1NTJ9.8fEKR6pzjgABI30HIMnjSZC9QdLc3kUAzIDzxk_XVdo
###
GET {{base-url}}/blogs HTTP/1.1
###
POST {{base-url}}/blogs HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "title": "title",
    "author": "author",
    "url": "asdasd.com",
    "likes": 10
}

###
DELETE {{base-url}}/blogs/5f5ca4808c7364691ce10540 HTTP/1.1
Authorization: Bearer {{token}}
###
POST {{base-url}}/users HTTP/1.1
Content-Type: application/json

{
    "name": "Riku Heinonen",
    "username": "rikuhh",
    "password": "password"
}
###
GET {{base-url}}/users HTTP/1.1

###
POST {{base-url}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "rikuh",
    "password": "password"
}